name: ShellCheck

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install -y shellcheck

      - name: Run ShellCheck
        run: |
          shellcheck *.sh
